export const QUOTES = [
  "The secret is to start.",
  "Small steps are still steps.",
  "Done is better than perfect.",
  "You don't have to see the whole staircase — just take the first step.",
  "Progress, not perfection.",
  "Break it until it's tiny. Then begin.",
  "The task is not as big as your brain thinks.",
  "One thing at a time. That's enough.",
  "Starting is the hardest part. You've done it before.",
  "Finished is better than flawless.",
  "What's the smallest possible version of this?",
  "You don't need motivation. You need a micro-step.",
  "Momentum builds from motion.",
  "The first two minutes are always the hardest.",
  "You can do anything for five minutes.",
  "Your only job right now is to start.",
  "Messy action beats perfect inaction.",
  "Tiny and done beats big and stuck.",
  "Focus is a practice, not a personality trait.",
  "One task. This task. Now.",
  "You've done hard things before. This is just the next one.",
  "Make it smaller until it's embarrassingly easy to start.",
  "It doesn't have to be perfect. It has to be done.",
  "The brain resists vague tasks. Make it concrete.",
  "Clarity, then action.",
  "What's the very next physical action?",
  "Stuck? Break it in half again.",
  "Beginning is its own reward.",
  "You can't steer a parked car.",
  "Ship it. Improve it. Keep going.",
  "The gap between starting and not starting is everything.",
  "Imperfect action beats paralysed perfection.",
  "Your future self will thank you for starting now.",
  "Done today beats perfect someday.",
  "Resistance is highest before you start. Push through it.",
  "Small wins compound.",
  "The work rewards those who show up.",
  "You don't have to feel ready. Just begin.",
  "Overwhelm is just too many tabs open. Close some.",
  "Pick one thing. Just one.",
  "Every expert was once a beginner who kept going.",
  "The hardest step is the first. The rest follow.",
  "A little progress every day adds up to big results.",
  "You've survived 100% of your hard days so far.",
  "It only has to be good enough to move forward.",
  "Focus is the new superpower.",
  "Subtract until it's obvious. Then act.",
  "Start before you're ready.",
  "The best time to start was earlier. The second best time is now.",
  "Complexity is the enemy of execution. Simplify.",
];
